---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hly.
--- DateTime: 2019/12/16 16:17
---
local insert = table.insert
local find = string.find
local type = type
local sub = string.sub
local gsub = string.gsub
local match = string.match
local lower = string.lower
local len = string.len

