---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hly.
--- DateTime: 2019/12/12 9:33
---
print("hello world ");

print(type(true))


local tbl = {"apple", "pear", "orange", "grape"}
for key, val in pairs(tbl) do
    print("Key", key)
end

module = {}

-- 定义一个常量


