---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hly.
--- DateTime: 2019/12/12 11:37
---
fruits = {"banana","orange","apple","grapes"}
print("排序前")
for k,v in ipairs(fruits) do
    print(k,v)
end

table.sort(fruits)
print("排序后")
for k,v in ipairs(fruits) do
    print(k,v)
end