---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hly.
--- DateTime: 2019/12/16 10:11
---
local insert = table.insert
local find = string.find
local type = type
local sub = string.sub
local gsub = string.gsub
local match = string.match
local lower = string.lower
local len = string.len

function to_conceal(value)
    if value then
        num = (#value) / 2;
        return gsub(value, sub(value, 1, num), "*****")
    end
    return value;
end

-- 字符串分割
function split(s, p)
    local rt = {}
    gsub(s, '[^' .. p .. ']+', function(w)
        table.insert(rt, w)
    end)
    return rt
end

function t(t,list)
    for i = 1, #list do
       t[list[i]] = v;
        
    end
end

print(to_conceal("a11sdasd"))
local list = split("data.mobile", ".")
print(list)
for i = 1, #list do
    print(list[i])
end



function findValueByTbl(tbl,key)--递归方法，用于查找tbl中对应的键值
    for k,v in pairs(tbl) do
        if k == key then
            if type(tbl[i])=="table" then--如果是table类型，递归查找
                return findValueByTbl(v,key)
            else
                return v
            end
        end
    end
end
